apiVersion: v1
kind: Service
metadata:
  name: php-webserver
  labels:
    app: php-webserver
spec:
  ports:
    - port: 80
      nodePort: 30002
  selector:
    app: php-webserver
    tier: frontend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-webserver
  labels:
    app: php-webserver
spec:
  selector:
    matchLabels:
      app: php-webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-webserver
        tier: frontend
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: php-webserver
        ports:
        - containerPort: 80
          name: php-webserver
        volumeMounts:
        - name: php-webserver-persistent-storage
          mountPath: /var/www/html/
      volumes:
      - name: php-webserver-persistent-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
