apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: prometheus-pvc
  labels:
    name: prometheuspvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grafana-pvc
  labels:
    name: grafanapvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
